spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ooap?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: vihunxi28

logging:
  level:
    root: info
    site.buzhou: debug
  file: log/blog-dev.log

mybatis:
  type-aliases-package: site.buzhou.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true